import '../domain/models/support_card.dart';
import '../domain/models/theme_card.dart';

final defaultThemeCards = [
  /// 生活面-------------------------
  ThemeCard(
    theme: '体調確認',
    category: '生活面',
    question: '残業多いと感じますか？仕事のボリュームはどうですか？',
    level: 1,
    remarks: 'しんどいなぁ、うまくいかないなと思うことがあったらぜひ教えてくださいませ',
  ),
  ThemeCard(
    theme: '体調確認',
    category: '生活面',
    question: '休日に休めていますか？よく寝れていますか？',
    level: 1,
    remarks: 'もし気が休めないとしたら不安なこと、焦っていること、気になることも少し話してみてください。',
  ),
  ThemeCard(
    theme: '体調確認',
    category: '生活面',
    question: '休みたい時に休めていますか？（ex: 有休など)',
    level: 2,
    remarks:
        'もし休めていなかったら、周りに気を遣ってしまう、いつも忙しくてタイミングがないなど要因になることを探りましょう。休むことも大切です。',
  ),
  ThemeCard(
    theme: '体調確認',
    category: '生活面',
    question: '仕事のこと考えすぎてないか心配なのですが、休みにどのくらい仕事のことを考えていますか？',
    level: 2,
    remarks: '仕事に夢中？逆にちょっと考えすぎてしまっているなど',
  ),

  ThemeCard(
    theme: '会社で働く中で感じることを共有',
    category: '生活面',
    question: '社内で気になることはありますか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: '会社で働く中で感じることを共有',
    category: '生活面',
    question: '会社生活で困っていること、戸惑っていることなどありますか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: '会社で働く中で感じることを共有',
    category: '生活面',
    question: '会社生活・仕事・それ以外も含めて不安なことはありますか？',
    level: 2,
    remarks: '教えてもらえることで配慮できること、一緒にできることがあるかもしれません。',
  ),

  /// 関係性-------------------------
  ThemeCard(
    theme: '職場での人間関係',
    category: '関係性',
    question: 'チーム（グループ）の状況はいかがですか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: '職場での人間関係',
    category: '関係性',
    question: '話しにくいなぁ、言いにくいなぁと思った状況が最近ありましたか？',
    level: 2,
    remarks: '言い損なってしまったけど、それが大事な情報な時も。今更と思わず、よかったら話してみてほしいです。',
  ),
  ThemeCard(
    theme: '職場での人間関係',
    category: '関係性',
    question: '自分の意見を聞き入れてもらえている感じがしますか？',
    level: 3,
    remarks: '',
  ),
  ThemeCard(
    theme: '職場での人間関係',
    category: '関係性',
    question: '仕事上今話しにくい人や苦手な人はいますか？',
    level: 3,
    remarks: '',
  ),

  /// 仕事関連-------------------------
  ThemeCard(
    theme: '仕事状況のヒアリング',
    category: '仕事関連',
    question: '今抱えている仕事が期限内に終わるのは何%ぐらいでしょうか？',
    level: 2,
    remarks: '50%のラインに行くには、80%のラインに行くには何日？どのくらいかかりそうでしょうか？',
  ),
  ThemeCard(
    theme: '仕事状況のヒアリング',
    category: '仕事関連',
    question: '今抱えている仕事はどこまで終わりましたか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '仕事状況のヒアリング',
    category: '仕事関連',
    question: '今抱えている仕事で不安な要素はありますか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '介入して一緒に解決する',
    category: '仕事関連',
    question: '今何を抱えていてどういう状態ですか？どこまではやりましたか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '介入して一緒に解決する',
    category: '仕事関連',
    question: 'どのくらい余裕がない状況で、どんな助けが必要でしょうか。',
    level: 2,
    remarks: 'うまく答えられなかったら別のテーマカードも一緒にみてくださいませ。',
  ),
  ThemeCard(
    theme: '介入して一緒に解決する',
    category: '仕事関連',
    question: '「やめてもいいもの」「遅らせられるもの」はありますか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '介入して一緒に解決する',
    category: '仕事関連',
    question: '他人に任せられることはありませんか？',
    level: 1,
    remarks: '',
  ),

  ThemeCard(
    theme: '仕事の解決を通じて成長する',
    category: '仕事関連',
    question: '仕事で困ったら聞く相手はいますか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: '仕事の解決を通じて成長する',
    category: '仕事関連',
    question: 'どこまで調べてみましたか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: '仕事の解決を通じて成長する',
    category: '仕事関連',
    question: '[書き出してみよう]やらないといけないことに対しての障害を確認しよう',
    level: 1,
    remarks: 'わからないことは？足りない情報は？足りないリソースは？',
  ),
  ThemeCard(
    theme: '過去の仕事から学びを得て成長する(1/4)',
    category: '仕事関連',
    question: '[書き出してみよう]振り返りたい期間に対してどんなことをやりましたか？',
    level: 1,
    remarks: '経験したことを時系列にストーリー（文章）で書いていきましょう！（例：ペアプロを導入して〇〇を作るのに〜した）',
  ),
  ThemeCard(
    theme: '過去の仕事から学びを得て成長する(2/4)',
    category: '仕事関連',
    question: '[書き出してみよう]振り返りたい期間から、どんなことを学びましたか？',
    level: 1,
    remarks:
        '目標に対する知見、過去の仕事と比較、やる前のイメージとの差、予想外だったことをヒントに文章で考えよう。（例：ペアプロをすることで他の人の思考を学ぶことができた）',
  ),
  ThemeCard(
    theme: '過去の仕事から学びを得て成長する(3/4)',
    category: '仕事関連',
    question: '[書き出してみよう]学んだことはどんな場面で使えそうでしょうか？',
    level: 1,
    remarks: '他の場面でも使える知識になるように学んだことを整理しよう（例：他の人とスキル共有する時にはペアプロを使ってみる）',
  ),
  ThemeCard(
    theme: '過去の仕事から学びを得て成長する(4/4)',
    category: '仕事関連',
    question: '[書き出してみよう]次に活かせる機会はどんなときでしょうか',
    level: 1,
    remarks: 'どんな時に活かせるか、やってみるかを考えていきましょう。（例：次のプロジェクト初期はペアプロを導入する）',
  ),

  ThemeCard(
    theme: '仕事を振り返る',
    category: '仕事関連',
    question: '今の仕事に意味や意義をどのくらい感じますか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '仕事を振り返る',
    category: '仕事関連',
    question: '仕事時間が「あっという間」に過ぎますか？',
    level: 1,
    remarks: '楽しくて「あっという間」と忙しさに忙殺されて「あっという間」では意味が異なるけど、どちらだろう？',
  ),
  ThemeCard(
    theme: '仕事を振り返る',
    category: '仕事関連',
    question: 'やりたいことが今の会社・部署で出来ていますか？',
    level: 2,
    remarks: 'やりたいことが特にない場合はキャリアのカードもみていきましょう',
  ),

  /// キャリア-------------------------
  ThemeCard(
    theme: '将来のイメージ',
    category: 'キャリア',
    question: '今後こうしていきたいといった目標を持っていますか？',
    level: 2,
    remarks: '方向性とかでも大丈夫。その目標にしたいなぁと思った理由やきっかけも教えてください。',
  ),
  ThemeCard(
    theme: '将来のイメージ',
    category: 'キャリア',
    question: '今後こんな風になりたいなぁというイメージはありますか？または憧れの人は？',
    level: 1,
    remarks: 'どんなところに憧れました？なぜいいなぁと思いましたか？',
  ),
  ThemeCard(
    theme: 'やりたいことを探っていこう',
    category: 'キャリア',
    question: '趣味のわくわく度を100点とした時仕事は何点ですか？',
    level: 2,
    remarks: 'ぜひその点数になった理由や、100点に足りない理由なども教えてください。どんな点が趣味と仕事で違いますか？',
  ),
  ThemeCard(
    theme: 'やりたいことを探っていこう',
    category: 'キャリア',
    question: '最近、あっという間に終わってしまったと感じた夢中になった仕事はなんですか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: 'やりたいことを探っていこう',
    category: 'キャリア',
    question: 'なぜ今の業界に興味を持ったのですか？',
    level: 1,
    remarks: 'どんなきっかけだったのかも聞かせてください！',
  ),
  ThemeCard(
    theme: 'やりたいことを探っていこう',
    category: 'キャリア',
    question: '学生時代などでどんなことが好きでしたか？',
    level: 1,
    remarks: '好きな理由や好きになったきっかけなどぜひあふれる思いを聞かせてくださいませ',
  ),
  ThemeCard(
    theme: 'やりたいことを探っていこう',
    category: 'キャリア',
    question: '何の制限もないとしたら、あなたがやりたいことはなんでしょうか？',
    level: 2,
    remarks: 'お金、人脈、スキル、時間など全ての条件がそろったとしたら・・・と想像してみてください。',
  ),
  ThemeCard(
    theme: 'やりたいことを探っていこう',
    category: 'キャリア',
    question: 'お金がいくらでもあってむしろ使ってほしいと言われたら、、、どんなことがしたいですか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: 'やりたいことを再確認しよう',
    category: 'キャリア',
    question: '今持っている目標以外に他の選択肢はありましたか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '実現方法を考えていこう',
    category: 'キャリア',
    question: 'この会社でどんなことを達成したいですか？身につけたいですか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '実現方法を考えていこう',
    category: 'キャリア',
    question: 'あなたがやりたいことに詳しい人はいますか？誰に聞けそうでしょうか。',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '価値観を知ろう',
    category: 'キャリア',
    question: '価値観が変わったなと思う体験はありますか？どんな体験でしたか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '価値観を知ろう',
    category: 'キャリア',
    question: '大事にしている価値観はありますか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: '価値観を知ろう',
    category: 'キャリア',
    question: '今の仕事の魅力は？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '価値観を知ろう',
    category: 'キャリア',
    question: '今の会社（部署・職種）を撰んだ理由は？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '価値観を知ろう',
    category: 'キャリア',
    question: '最近どんな出来事に感情が揺れましたか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '自分が「できること」を探る',
    category: 'キャリア',
    question: 'あなたの得意なことを教えてください。',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '自分が「できること」を探る',
    category: 'キャリア',
    question: 'あなたが世の中の役に立っていると思うことは何ですか？',
    level: 2,
    remarks: '',
  ),
  ThemeCard(
    theme: '自分が「できること」を探る',
    category: 'キャリア',
    question: '今までに上司やメンバーから褒められた・感謝されたエピソードはありますか？',
    level: 1,
    remarks: '',
  ),
  ThemeCard(
    theme: '自分が「できること」を探る',
    category: 'キャリア',
    question: '失敗を乗り越えたエピソードはありますか？',
    level: 2,
    remarks: '乗り越えた経験がないよと思うかもしれません。けれども何らかうまく回避して今があるはず。どう切り抜けましたか？',
  ),
];

final defaultSupportCards = [
  SupportCard(
    situation: 'フィードバック: 使えたいことがある場(1/3)',
    level: 2,
    advice: '何が起きたのかを説明',
    remarks: 'どんな「状況」でどんな「行動」をしてどんな「結果」が起きた？プロセスや結果に着目し事実から伝えます。',
  ),
  SupportCard(
    situation: 'フィードバック: 使えたいことがある場(2/3)',
    level: 2,
    advice: '私は〜と思う',
    remarks: '一般論などは言わず「I(私)のメッセージ」で伝えましょう。評価や判断はその情報を効いた本人に委ねましょう',
  ),
  SupportCard(
    situation: 'フィードバック: 使えたいことがある場(3/3)',
    level: 2,
    advice: 'あなたはどう思う？',
    remarks: '伝えた内容がどのように相手に届いたか確認。どう思うかを問いかける',
  ),
  SupportCard(
    situation: '相談内容を引き出す',
    level: 2,
    advice: '解決したいことはどんなことでしょうか？',
    remarks: '具体的には何を解決したいですか？今回の相談でのゴールはどこに設定しましょうか。',
  ),
  SupportCard(
    situation: '相談内容を引き出す',
    level: 1,
    advice: 'できたこと、やったことはどんなことですか？',
    remarks: 'どんなことを試してみてどんな結果になりましたか？試行錯誤の過程をぜひ教えてください。',
  ),
  SupportCard(
    situation: '相談内容を引き出す',
    level: 2,
    advice: '悩んでいることをより具体的にしましょう',
    remarks: 'どんなところに困っていたり、詰まったりしていますか？',
  ),
  SupportCard(
    situation: '相談内容を引き出す',
    level: 2,
    advice: '選択肢を見直そう',
    remarks: '今までやってきた選択肢意外にありますか？「誰かに手伝ってもらう」「新たな手段を試す」など・・・',
  ),
  SupportCard(
    situation: '話しにくそうな時に',
    level: 1,
    advice: 'うまく話せなくても大丈夫なのでゆっくり話してみませんか？',
    remarks: '',
  ),
  SupportCard(
    situation: '話しにくそうな時に',
    level: 1,
    advice: 'どんな些細なことでも構いません。話してもらえませんか？',
    remarks: '',
  ),
  SupportCard(
    situation: '話しにくそうな時に',
    level: 1,
    advice: '思いついたことを話してもらってもいいでしょうか？',
    remarks: '前提として「まとまっていなくても大丈夫」「一緒に整理しましょう」といった声かけも話しやすくなりますね。',
  ),
  SupportCard(
    situation: '深ぼって聴いてみる',
    level: 2,
    advice: '共通点はありますか？',
    remarks: '共通点を探ることによって抽象化することができ、似たような出来事の時にも活かしやすくなります。',
  ),
  SupportCard(
    situation: '深ぼって聴いてみる',
    level: 1,
    advice: 'もう少し詳しく話してもらえますか？',
    remarks:
        '理解したいので「イメージがもっとしやすいようにしたい」「具体的に聞かせてほしい」といったメッセージを添えると聴いてくれている姿勢が伝わりやすいですよ。',
  ),
  SupportCard(
    situation: '深ぼって聴いてみる',
    level: 2,
    advice: '障害となっているものはありますか？',
    remarks: '',
  ),
  SupportCard(
    situation: '深ぼって聴いてみる',
    level: 2,
    advice: '事実と解釈を分けてみよう',
    remarks:
        '起きたことなのか、その起きたことに対する解釈かを整理してみよう。（例：〇〇に怒られたのでもういらない人間だと思われた。⇨怒られたことは事実。いらないと言われたのは事実？そう思っただけ？',
  ),
  SupportCard(
    situation: '深ぼって聴いてみる',
    level: 2,
    advice: '私にお手伝いできることはありませんか？',
    remarks: '「情報提供」「チームや上層部への掛け合い」「間に入ってほしい」など',
  ),
  SupportCard(
    situation: '深ぼって聴いてみる',
    level: 2,
    advice: 'どんな材料があったらできそうですか？',
    remarks: '例：人、もの、期間、お金など',
  ),
];
